import './globals.css';
import Header from "@/components/Navbar/Header";
import Footer from "@/components/footer/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased flex flex-col min-h-screen`} style={{ fontFamily: "'Glacial Indifference', sans-serif" }}>
        <nav>
          <Header />
        </nav>
        <main className="flex-grow">
          {children}
        </main>
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
